<style>
        table tr th,table tr td{
        padding: 5px;
        border: solid 1px #CCC;
        width:95%;
        
    }
    
    table tr th{
        background: #e4e4e4;
        font: bold 0.9em Arial, Helvetica, san-serif;
        color: #666;
        
    }
    
    table tr td{
        font: 0.85em Arial, Helvetica, san-serif;
        color: #333;
        
    }
    
    table tr:nth-child(2n+1){
        background: #f1f1f1;
    }
    
        form input[type="text"],input[type="email"] {
	
	outline: none;
	background: none;
	font-size:12px;
	color: #acacac;
	width:100%;
	padding:5px;
}
        form input[type="button"] {
	
	cursor: pointer;
	background: url(../images/search.png) no-repeat 0px 7px;
	position: absolute;
	font-size: 30px;
	width: 100%;
	
}
    
    
</style>
<?php
echo '<table border="2"><th>#</th><th>Category</th><th colspan="2">Action</th>';;
for($i=0;$i<count($this->categorys);$i++)
{
    $x=$i+1;
    echo"<tr>";
    echo "<td>".$x."</td>";
    echo "<td>".$this->categorys[$i]['category_name']."</td>";
    echo '<td><a href="'.$this->baseUrl().'/admin/deletecategory/id/'.$this->categorys[$i]['category_id'].'">Delete</a></td>';
    echo"</tr>";
}
echo '</table>';

?>