
<style>
        table tr th,table tr td{
        padding: 5px;
        border: solid 1px #CCC;
        width:95%;
        
    }
    
    table tr th{
        background: #e4e4e4;
        font: bold 0.9em Arial, Helvetica, san-serif;
        color: #666;
        
    }
    
    table tr td{
        font: 0.85em Arial, Helvetica, san-serif;
        color: #333;
        
    }
    
    table tr:nth-child(2n+1){
        background: #f1f1f1;
    }
    
        form input[type="text"],input[type="email"] {
	
	outline: none;
	background: none;
	font-size:12px;
	color: #acacac;
	width:100%;
	padding:5px;
}
        form input[type="button"] {
	
	cursor: pointer;
	background: url(../images/search.png) no-repeat 0px 7px;
	position: absolute;
	font-size: 30px;
	width: 100%;
	
}
    
    
</style>


<?php

echo '<table border="2"><th>Product</th><th>Price</th><th>Image</th><th colspan="3">Action</th>';;
for($i=0;$i<count($this->products);$i++)
{
    
    echo"<tr>";
    echo "<td>".$this->products[$i]['product_name']."</td>";
    echo "<td>".$this->products[$i]['price']." pounds</td>";
    echo '<td><img src="'.$this->baseUrl("upload/".$this->products[$i]['product_image']).'" width="100" height="100"></td>';
    echo "<td>".$this->products[$i]['avaliable']."</td>";
    echo '<td><a href="'.$this->baseUrl().'/admin/edit/id/'.$this->products[$i]['product_id'].'">Edit</a></td>';
    echo '<td><a href="'.$this->baseUrl().'/admin/delete/id/'.$this->products[$i]['product_id'].'">Delete</a></td>';
    echo"</tr>";
}
echo '</table>';

?>
