<!DOCTYPE html>
  
<?php
        $auth = Zend_Auth::getInstance();
        if ($auth->hasIdentity()) {
            $this->name = $auth->getIdentity()->name;
            } else {
                $this->name = "admin";
            }
?>  
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
<title>ELSAWAF CAFE Admin Panel</title>
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl()."/css/reset.css" ?>" />
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl()."/css/layout.css"?>"  />
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl()."/css/supersized.shutter.css"?>" />
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl()."/css/menu.css"?>"  />
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl()."/css/font-awesome.css"?>"  />
<link rel="stylesheet" type="text/css" href='http://fonts.googleapis.com/css?family=Leckerli+One'  />	
<link rel="stylesheet" type="text/css" href='http://fonts.googleapis.com/css?family=Viga' />
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl()."/style.css"?>"  />
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl()."/css/responsive.css"?>"  />
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl()."/css/supersized.3.2.7.css"?>"  />

<!--this is what needs to be handled-->

    <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl()."/bootstrap/css/bootstrap.min.css"?>" />
    <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl()."/font-awesome/css/font-awesome.min.css"?>" />

</head>
<body>
    <style>
        body{
        background-color: #EEF261;
    }
        
    </style>
    <nav class="menu nav_wrapper" id="myslidemenu">
        
        <!--Profile Picture-->
        <ul class="nav navbar-nav navbar-right">
            <li><img id ="profile-img" href="index/index" src="<?= $this->baseUrl()."/images/profile.jpg"?>" width = "42" height="47"/></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><?= $this->name ?> <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="<?= $this->baseUrl() . "/index/logout" ?>">Sign out</a></li>
                    </ul>
                </li>
            </ul>
        
        <!--Search bar-->
    <div class="col-sm-3 col-md-3 pull-left">
        <form class="navbar-form" role="search">
             <div class="input-group">
                 <input type="text" class="form-control" placeholder="Search" name="q">
                 <div class="input-group-btn">
                      <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                 </div>
             </div>
        </form>
    </div>
        
    </nav>


<!--Logo Start-->
<section id="logo" style="">
	<h1 style="font-size: 90px;">ELSAWAF CAFE</h1>
    <h4>WELCOME TO ELSAWAF CAFETERIA</h4>
</section>
<!--Logo End-->

<!--Menu Start-->
<nav class="menu nav_wrapper" id="myslidemenu">
    <ul class="menu" id="jqueryslidemenu">
        <li><a href="<?= $this->baseUrl()."/admin/" ?>"><i class="fa fa-home"></i>Home</a></li>
        
        <li  class="current"><a href="<?= $this->baseUrl()."/admin/listcategory" ?>"><i class="fa fa-cutlery"></i>Categories</a>
        	<ul class="sub-menu">
            	<li><a href="<?= $this->baseUrl()."/admin/addcategory" ?>">Add Category</a></li>
            </ul>
        </li>
        
        
        <li  class="current"><a href="<?= $this->baseUrl()."/admin/list" ?>"><i class="fa fa-cutlery"></i>Products</a>
        	<ul class="sub-menu">
            	<li><a href="<?= $this->baseUrl()."/admin/add" ?>">Add Product</a></li>
            </ul>
        </li>
        <li  class="current"><a href="<?= $this->baseUrl()."/admin/indexuser" ?>"><i class="fa fa-cutlery"></i>Users</a>
            <ul class="sub-menu">
            	<li><a href="<?= $this->baseUrl()."/admin/adduser" ?>">Add User</a></li>
            </ul>
        </li>
        <li><a href="<?= $this->baseUrl()."/admin/add-order" ?>"><i class="fa fa-comments"></i>Manual Order</a></li>
        <li><a href="<?= $this->baseUrl()."/admin/checks" ?>"><i class="fa fa-phone-square"></i>Checks</a></li>
        <li><a href="<?= $this->baseUrl()."/myorder/listmyyorder" ?>"><i class="fa fa-phone-square"></i>Add Order</a></li>
    </ul>
    
   
</nav>
<!--Menu End-->
<br>

<?php echo $this->layout()->content; ?>


<!--Footer Start-->
<footer class="well"style = "border-radius: 0; background-color: #ccc;bottom:0;margin-bottom:0;margin-top:50px; height: 80px ">
            <div class="container">
                <div class ="row">
                    <div class="col-sm-6">
                        <p>Call Us : 012 - 7672 - 4960 Email Us : support@sawafcafee.com	</p>
                    </div>
                    <div class="col-sm-3">
                        <p class="copy-right">© All Rights Reserved by SawafCafee</p>
                    </div>
                    <div class="col-sm-3">
                        <ul class = "list-inline">
                            <li><i class="fa fa-twitter"></i></li>
                            <li><i class="fa fa-facebook"></i></li>
                            <li><i class="fa fa-rss"></i></li>
                            <li><i class="fa fa-youtube"></i></li>
                            <li><i class="fa fa-linkedin"></i></li>
                        </ul>
                    </div>  
                </div>
            </div>       
        </footer>
<!--Footer End-->
<script type="text/javascript" src="<?= $this->baseUrl()."/js/jquery.js"?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl()."/js/jquery.easing.min.js"?>"></script>		
<script type="text/javascript" src="<?= $this->baseUrl()."/js/supersized.3.2.7.js"?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl()."/js/supersized.shutter.js"?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl()."/js/superized-custom.js"?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl()."/js/custom.js"?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl()."/js/jquery-1.10.2.min.js"?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl()."/bootstrap/js/bootstrap.min.js"?>"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="http://silviomoreto.github.io/bootstrap-select/javascripts/bootstrap-select.js"></script>

<script>
jQuery(document).ready(function($) {
   'use strict';
    
$("#owl-demo").owlCarousel({ 
autoPlay: false, //Set AutoPlay to 3 seconds 
items : 6,
itemsDesktop : [1199,3],
itemsDesktopSmall : [979,3],
pagination: false 
});

});
</script>
<script>
jQuery(document).ready(function($) {
   'use strict';
$("a[data-gal^='prettyPhoto']").prettyPhoto({hook: 'data-gal'});
});
</script>
      <script type="text/javascript">
$(".dropdown-menu li a").click(function(){
  var selText = $(this).text();
  $(this).parents('.btn-group').find('.dropdown-toggle').html(selText+' <span class="caret"></span>');
});

$("#btnSearch").click(function(){
	alert($('.btn-select').text()+", "+$('.btn-select2').text());
});
      </script>
</body>


</html>

    
    
    
    
    
    
    