<section id="my-content">
    <div class="container">
        <div class="row center-block">
            
            <div class="breadcrumbs">
                <ol class="breadcrumb">
                    <li><a href="#">Home</a></li>
                    <li class="active">All Users</li>
                </ol>
            </div><!--/breadcrums-->
            
            <div class="col-sm-12" style="text-align:right; padding: 10px 0;">
                <a href="<?= $this->baseUrl()."/users/add"?>" class="btn btn-default" title="add user"><i class = "fa fa-plus"></i></a>
                
            </div>
            
            <table class="table text-center" id="cafe-order" style="width:100%">
                <tr>
                    <th>IMAGE</th>
                    <th>NAME</th>
                    <th>ROOM NO.</th>
                    <th>EXT.</th>
                    <th colspan = '2'>ACTION</th>
                </tr>
                <?php
                    $list = $this->users;
                    for($i = 0 ; $i < count($list); $i++){
                    ?>
                <tr>
                    <td><img src="<?= $this->baseUrl()."/avatars/".$list[$i]['image'] ?>" width="50" style="border: 1px solid #D0F6F9;border-radius: 3px;"/></td>
                    <td><?= $list[$i]['name'] ?></td>
                    <td><?= $list[$i]['room_no'] ?></td>
                    <td><?= $list[$i]['ext'] ?></td>
                    <td><a href='<?= $this->baseUrl()."/users/edit/id/".$list[$i]['user_id'] ?>' style="color: #FFB800; font-size:20px;"><i class="fa fa-edit"></i></a></td>
                    <td><a href='<?= $this->baseUrl()."/users/delete/id/".$list[$i]['user_id'] ?>' style="color: #FFB800;font-size:20px;"><i class="fa fa-times"></i></a></td>
                </tr>
                <?php
                }   
                ?>    
            </table>
            
        </div>
    </div>
</section>
