<link rel="stylesheet" href="<?= $this->baseUrl() ?>/css/style.css" />
<!--<script src="<?= $this->baseUrl() ?>/js/order.js"></script>
<div id="prod">
    <h1>hello</h1>
</div>
<div id="choose">
    <h1>choose</h1>
    <table style="border: 2px solid black">
<?php
echo $this->ddd;    

//for($i=0;$i<count($this->viewed);$i++){
//    echo '<tr ><td><button id="'.$i.'">'.$this->viewed[$i]['name'].'</button></td><td>'.$this->viewed[$i]['image'].'</td></tr>';
//}
?>
</table>
</div>
<div id="head">
    <h1>head</h1>
</div>-->